- Etabs_Adapter/Helpers/Results.cs
Fixes #111  
There's some funny commit history that I hope will dissapear in the merge, because I accidentally committed into a local copy of the last branch which had just been merged, then merged into the new branch to fix it. If you'd rather I started fresh, let me know.
**PREVIOUSLY PR'ED HERE:**
https://github.com/BHoM/ETABS_Toolkit/pull/112
Re PR'ed here to solve the rebase/merge issue for @IsakNaslundBh
> Etabs toolkit issue111 do not ignore ids and cases for bar force

- ETABS_Engine/Convert/ToBHoM.cs
- ETABS_Engine/Convert/ToETABS.cs
- ETABS_Test/Program.cs
- Etabs_Adapter/CRUD/Create.cs
- Etabs_Adapter/CRUD/Read.cs
https://github.com/BHoM/BHoM/pull/395
https://github.com/BHoM/BHoM_Engine/pull/776
Closes #120 
Aligning with changes to the Node class in the BHoM
Any of the sample files as well as any of the previously working scripts.
- All methods affected by `Node` class property change made in https://github.com/BHoM/BHoM/pull/395 updated. No change made to any of the method interfaces
> Aligning with changes to the Node class

- Etabs_Adapter/CRUD/ReadResults.cs
- Etabs_Adapter/Helpers/Results.cs
Added extract method for Global Reactions.
Closes #154 
https://burohappold.sharepoint.com/:u:/s/BHoM/ESIF-wBKmJNJhN_MPxLBVwgBnP6ZdLg9VgKXsOIENUMAhQ?e=2deKAf
> Added extract method for Global Reactions

- ETABS_Test/Program.cs
- Etabs_Adapter/CRUD/Read.cs
- Etabs_Adapter/Helpers/Results.cs
Closes #171 
Reading of Etabs Meshes implemented.
Also first implementation of reading meshStresses. Please check that what I ahve done makes sense for this.
General cleanup of case setup into one centralised method.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Etabs_Toolkit-Issue171-ReadMeshes?csf=1&e=twTfxQ
fyi @nirbhay93 @dlamianski
> Etabs toolkit issue171 read meshes

- ETABS_Test/ETABS_Test.csproj
- ETABS_Test/Program.cs
https://github.com/BHoM/BHoM/pull/509
Closes #178 
Renaming Queries to Request. Only change in testproject, non in the production code
> Query to Request in Test project

- .github/ISSUE_TEMPLATE/api_changed.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/compliance.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/test_script.md
Fixes #180  
N/A
- Added IssueTemplates
> ETABS_Toolkit: Issue templates

- ETABS_Engine/Properties/AssemblyInfo.cs
- ETABS_Test/Properties/AssemblyInfo.cs
- ETABS_oM/Properties/AssemblyInfo.cs
- Etabs_Adapter/Properties/AssemblyInfo.cs
Closes #182 
Updates the `AssemblyFileVersion` to `2.3.0.0`
> ETABS_Toolkit: Update Assembly File Version

- Etabs_Adapter/Create/Bar.cs
Closes #95 
Closes #115 
Added empty method to return an error when freeform sections are pushed.
https://burohappold.sharepoint.com/:f:/s/BHoM/EklL7re8IQlEklJhWb7faKYByNQUYRfVg2HLRUenPbQIVA?e=3ufgXE
> Issue95 added empty method for freeform profiles

- ETABS_Engine/Properties/AssemblyInfo.cs
- ETABS_oM/Properties/AssemblyInfo.cs
- Etabs_Adapter/Properties/AssemblyInfo.cs
Closes #224 
Make sure that:
- All the .csproj files in the solution have the properties  `AssemblyFileVersion` to `3.0.0.0` and `AssemblyVersion` to `3.0.0.0`.
- The AssemblyCopyright reads `[assembly: AssemblyCopyright("Copyright © https://github.com/BHoM")]`
- Update `AssemblyFileVersion` to `3.0.0.0`
- Update `AssemblyVersion` to `3.0.0.0`
> Update AssemblyVersion and AssemblyFileVersion to 3.0.0.0

- Etabs_Adapter/Read/Bar.cs
Closes #107 
Pulls the orientationAngle for bars as well now
https://burohappold.sharepoint.com/:u:/s/BHoM/EcdTuZ9gtAZGqeTqj-E2uUIB6l1XnsfK9BxqFPpQQKRtwA?e=MTu7Lq
Think advanced would be if it isn't only rotated along the bar, but it was out of the scope of this PR, maybe flag an issue for later?
> Read Orientation angle for Bars

- ETABS_Engine/Properties/AssemblyInfo.cs
- ETABS_oM/Properties/AssemblyInfo.cs
- Etabs_Adapter/Properties/AssemblyInfo.cs
Closes #244
Update assembly file version to 3.1
> Update assembly version to 3.1

- ETABS_Engine/ETABS_Engine.csproj
- ETABS_Engine/Modify/SetAutoLengthOffset.cs
- ETABS_Engine/Modify/SetInsertionPoint.cs
- ETABS_Engine/Query/AutoLengthOffset.cs
- ETABS_Engine/Query/InsertionPoint.cs
- ETABS_oM/ETABS_oM.csproj
- ETABS_oM/Fragments/AutoLengthOffset.cs
- ETABS_oM/Fragments/InsertionPoint.cs
- Etabs_Adapter/Create/Bar.cs
Closes #245 
allows one to access this: 
in BHoM, 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Issue_245%20ModifyStiffness%20for%20SetInsertionPoint/Issue_245%20ModifyStiffness%20for%20SetInsertionPoint.gh?csf=1&e=Bckfd8
> Option to modify stiffness for set insertion point

- ETABS_oM/ETABS_oM.csproj
- ETABS_oM/Fragments/EtabsLabel.cs
- Etabs_Adapter/CRUD/Read/Bar.cs
- Etabs_Adapter/CRUD/Read/Node.cs
- Etabs_Adapter/CRUD/Read/Panel.cs
Closes #166 
https://burohappold.sharepoint.com/:f:/s/BHoM/EnT2Ig_5O0xHhRK3OuMaMx0B-QD1_ckAuJS-UFXZUpALmA?e=8MAfZp
- Adding EtabsLabel fragment to the Etabs_oM to store Label and Story information
- Assigning this label to Bars, Panels and Nodes on Read
> Pull labels and stories for Bars, Panels and Nodes

- ETABS_Engine/ETABS_Engine.csproj
- Etabs_Adapter/Etabs_Adapter.csproj
https://github.com/BHoM/BHoM/pull/704
https://github.com/BHoM/BHoM_Engine/pull/1484
https://github.com/BHoM/BHoM_Adapter/pull/193
Closes #269 
Adds references to Dimensional_oM where necessary and 'using' statments where that is necessary 
to comply with the changes in https://github.com/BHoM/BHoM/pull/704
> Update IElement references with the Dimensional_oM

- Etabs_Adapter/CRUD/Read/SectionProperty.cs
Closes #272 
As title
https://burohappold.sharepoint.com/:f:/s/BHoM/Ej_rYko6nTRAimPc-p-jB9kByy6_5vYui6nR3dZQTrWR0w?e=WWXRWz
> Fix T-section height not pulled correctly

- ETABS_oM/Fragments/AutoLengthOffset.cs
- ETABS_oM/Fragments/EtabsLabel.cs
- ETABS_oM/Fragments/InsertionPoint.cs
https://github.com/BHoM/BHoM/pull/711
https://github.com/BHoM/BHoM_Engine/pull/1495
Fixes #274
> Renaming IBHoMFragment -> IFragment

- Etabs_Adapter/CRUD/Create/Load.cs
- Etabs_Adapter/CRUD/Read/Load.cs
Closes #265 
Add support for local axis and projected for load push/pull, with some increased error messaging and centralising of some functionality 
https://burohappold.sharepoint.com/:u:/s/BHoM/EZ5ZTwyiB4NGkUDRa-VYxegBDVEjnkimpDNJgQsNfsb7_Q?e=ck2W8v
> Add support for local axis and projected for load push/pull

- Etabs_Adapter/CRUD/Read/Grid.cs
- Etabs_Adapter/CRUD/Read/_Read.cs
- Etabs_Adapter/Etabs_Adapter.csproj
Closes #167 
Allows one to pull Grids.
https://burohappold.sharepoint.com/:f:/s/BHoM/ErtGvZWnFulIt40Isz-1pNkB46Y_w0eQBAKLSOnfpAdt8Q?e=X0Oh4P
> Pulling Grids Enabled

- Etabs_Adapter/CRUD/Create/_Create.cs
https://github.com/BHoM/BHoM_Adapter/pull/214
Closes #284 
Not needed.
> Align to BHoM_Adapter PushType renaming: from FullCRUD to FullPush

- Etabs_Adapter/CRUD/Read/SectionProperty.cs
Closes #286 
Better to try get value instead of throwing errors.
Test file here can be used as an example:
https://burohappold.sharepoint.com/:f:/s/BHoM/EkXvc8ZBXOZNr7HhmSEuzW8BS6e5UN6hCkJMXHCfO2E3Xg?e=XaRhmC
> Changing from try-catch to tryGetValue for getting materials for sections

- ETABS_Engine/ETABS_Engine.csproj
- Etabs_Adapter/Etabs_Adapter.csproj
> Remove version from referenced dlls

- Etabs_Adapter/CRUD/Create/SectionProperty.cs
- Etabs_Adapter/CRUD/Create/SurfaceProperty.cs
- Etabs_Adapter/CRUD/Read/Panel.cs
- Etabs_Adapter/CRUD/Read/SectionProperty.cs
- Etabs_Adapter/CRUD/Read/SurfaceProperty.cs
- Etabs_Adapter/CRUD/Update/SectionProperty.cs
- Etabs_Adapter/Etabs_Adapter.csproj
https://github.com/BHoM/BHoM/pull/895
https://github.com/BHoM/BHoM_Engine/pull/1809
Closes #316
Make use of the new Modifer fragments that formalises better the handling of modifiers for section and surface properties.
https://burohappold.sharepoint.com/:f:/s/BHoM/Eu9KlRRcXutFpuq8lDebZN8BI7DDlOioLqpXBFJ4bWKb-w?e=L0Iby5
> Make modifiers use new Fragment

- ETABS_Engine/ETABS_Engine.csproj
- ETABS_oM/ETABS_oM.csproj
- Etabs_Adapter/CRUD/Read/Results/BarResults.cs
- Etabs_Adapter/CRUD/Read/Results/GlobalResults.cs
- Etabs_Adapter/CRUD/Read/Results/MeshResults.cs
- Etabs_Adapter/CRUD/Read/Results/NodeResults.cs
- Etabs_Adapter/CRUD/Read/Results/Result.cs
- Etabs_Adapter/Etabs_Adapter.csproj
https://github.com/BHoM/BHoM/pull/911
Aligning with migration of Results from Common_oM to Analytical_oM.
Also, removing reference to Common_oM as no longer needed.
> Aligning with changes migrating Results to Analytical_oM

- Etabs_Adapter/CRUD/Create/Load.cs
- Etabs_Adapter/CRUD/Read/Load.cs
> Fix all load types returned when trying to pull not yet implemented load type

- Etabs_Adapter/CRUD/Update/Panel.cs
- Etabs_Adapter/CRUD/Update/_Update.cs
Closes #325 
Fix the dispatching done by the Update method
https://burohappold.sharepoint.com/:f:/s/BHoM/EqKCe0ee8wROoq24ANb0-r0BTUvkH_h4vJ8kHiyFesXtKw?e=tp6GTX
https://burohappold.sharepoint.com/:f:/s/BHoM/EgLyzStwfWpGi7sSnAxSKNYBIyRhMp90JNyRQ_ozaUD-9g?e=ggV4Jt
> Fix the dispatching done by the Update method

- Etabs_Adapter/CRUD/Read/Results/BarResults.cs
- Etabs_Adapter/CRUD/Read/Results/MeshResults.cs
- Etabs_Adapter/CRUD/Read/Results/NodeResults.cs
- Etabs_Adapter/CRUD/Read/Results/Result.cs
Closes #338
Making sure ObjectIds can be objects of the appropriate type, looking for the Id information on the said obecjts.
https://burohappold.sharepoint.com/:f:/s/BHoM/EszNjShmWNFJpiMmQ1EdM7ABAa3i7rfMe8oa54uHFtbwxg?e=I2rfcN
> Enable filtering by Objects when reading results 

- Etabs_Adapter/CRUD/Read/Results/Result.cs
Closes #344
Adding missing else in CheckAndGetIds
> Adding missing else on check and get ids

- Etabs_Adapter/CRUD/Create/SectionProperty.cs
- Etabs_Adapter/CRUD/Read/SectionProperty.cs
- Etabs_Adapter/Etabs_Adapter.csproj
https://github.com/BHoM/BHoM/pull/1030
https://github.com/BHoM/BHoM_Engine/pull/2063
Related to https://github.com/BHoM/BHoM/issues/756
- Aligning with migration of shape profiles from Geometry to Spatial
> Aligning with changes to ShapeProfiles

- ETABS_Engine/ETABS_Engine.csproj
- ETABS_Engine/Modify/SetDiaphragm.cs
- ETABS_Engine/Modify/SetPier.cs
- ETABS_Engine/Modify/SetShellType.cs
- ETABS_Engine/Modify/SetSpandrel.cs
- ETABS_Engine/Query/Diaphragm.cs
- ETABS_Engine/Query/Pier.cs
- ETABS_Engine/Query/Spandrel.cs
- ETABS_oM/ETABS_oM.csproj
- ETABS_oM/Elements/Diaphragm.cs
- ETABS_oM/Elements/Pier.cs
- ETABS_oM/Elements/Spandrel.cs
- ETABS_oM/Fragments/ShellTypeFragment.cs
- Etabs_Adapter/CRUD/Create/SurfaceProperty.cs
- Etabs_Adapter/CRUD/Read/SurfaceProperty.cs
Closes #355 
Removing use of custom data by:
- Turning Diaphragm, Pier and Spandrel into fragments and aligning methods
- Adding a ShellTypeFragment
> Remove custom data

- Etabs_Adapter/CRUD/Create/Load.cs
- Etabs_Adapter/CRUD/Read/Load.cs
https://github.com/BHoM/BHoM/pull/1074
https://github.com/BHoM/BHoM_Engine/pull/2138
- Align with changes from `BarTemperatureLoad` and `AreaTemperatureLoad` to `BarUniformTemperatureLoad` and `AreaUniformTemperatureLoad`
> Align with changes to BarUniformTemperatureLoad and AreaUniformTemperatureLoad

- ETABS_Engine/Query/InsertionPoint.cs
- ETABS_Engine/Query/ModifyStiffnessInsertionPoint.cs
- Etabs_Adapter/CRUD/Create/Bar.cs
- Etabs_Adapter/CRUD/Create/Error.cs
- Etabs_Adapter/CRUD/Create/Link.cs
- Etabs_Adapter/CRUD/Create/Material.cs
- Etabs_Adapter/CRUD/Create/Node.cs
- Etabs_Adapter/CRUD/Create/Panel.cs
- Etabs_Adapter/CRUD/Create/SectionProperty.cs
- Etabs_Adapter/CRUD/Create/SurfaceProperty.cs
- Etabs_Adapter/CRUD/Create/_Create.cs
Closes #351 
Better null checks and messaging for create methods
Testing pushing null obejcts:
https://burohappold.sharepoint.com/:f:/s/BHoM/Ejl-ro8QLd5Elncm9J8H8CQBHkZtHtJZs3V8Ue9xNlGvEg?e=wTbxKf
General element pushing:
https://burohappold.sharepoint.com/:f:/s/BHoM/El7OJUjBcChDoP3yldO0MCsB5gcD_GiuUajIwXKZVQFKbA?e=gBHMx7
Push-pull-compare test
https://burohappold.sharepoint.com/:f:/s/BHoM/Ekjy6DnHUihOtkoMtrwv-pYBbCGgpeL5CP9FOxYGe37zDQ?e=WlGxj5
> Better nullchecks on create methods

- Etabs_Adapter/CRUD/Create/Panel.cs
- Etabs_Adapter/CRUD/Read/Load.cs
https://github.com/BHoM/BHoM_Engine/pull/2146/
https://github.com/BHoM/BHoM_Engine/issues/2135
Aligning with methods being removed from Structure_Engine.
This is only adding an additional using, so can safely be merged before others.
> Aligning with changes in Structure_Engine

- Etabs_Adapter/CRUD/Create/Load.cs
- Etabs_Adapter/CRUD/Read/Load.cs
https://github.com/BHoM/BHoM/pull/1075
https://github.com/BHoM/BHoM_Engine/pull/2160
Aligns with changes to the BarVaryingDistributedLoad.
https://burohappold.sharepoint.com/:f:/s/BHoM/Eha-mq-0l55KryMeBe543YkBf2M6CQUaOaL6xgKfeFLg6Q?e=rIb1yO
> Update bar varying distributed loads

- ETABS_oM/Versioning_40.json
Closes #365 
Fix typo
https://burohappold.sharepoint.com/:f:/s/BHoM/Elq_M6MW02RMrXi0ybJGk9sBdUrDIslY_Mc_cQTIf_CzrQ?e=9YV1gY
> Fix typo in ETABSId verisoning

- Etabs_Adapter/AdapterActions/Execute.cs
https://github.com/BHoM/BHoM_Adapter/pull/303
Closes #387
Adding support for the Exit command
https://burohappold.sharepoint.com/:f:/s/BHoM/EjpTgU6jo_tJr30rbJs0a_gBnZnhI1rYcv3aQ-Yc3A6E2g?e=fenJ0J
> Add implementation of Exit command

- Etabs_Adapter/CRUD/Read/Node.cs
- Etabs_Adapter/CRUD/Read/Panel.cs
Done is support of, but compiles without https://github.com/BHoM/BHoM_Engine/pull/2738
Align with removed methods from Structure_Engine
> Align with changes in Structure_Engine

- ETABS_Engine/Properties/AssemblyInfo.cs
- ETABS_oM/Properties/AssemblyInfo.cs
- Etabs_Adapter/Properties/AssemblyInfo.cs
Update Assembly Information to include description
> Update Assembly Information

- Etabs_Adapter/CRUD/Read/Bar.cs
> Added bar insertion point to ETABS bar

- Etabs_Adapter/CRUD/Read/Bar.cs
> Added group assignments to ETABS bar

- Etabs_Adapter/CRUD/Update/Bar.cs
Closes #424
Correct check for adapter id for Bar update
> Fix boolean check on Bar update

- ETABS_Engine/Query/CheckFlipBar.cs
- Etabs_Adapter/CRUD/Create/Bar.cs
- Etabs_Adapter/CRUD/Read/Bar.cs
- Etabs_Adapter/CRUD/Update/Bar.cs
https://github.com/BHoM/BHoM/pull/1579
> Align with rename StartNode/EndNode to Start/End

- ETABS_oM/Results/PierForce.cs
Closes #446 
check code-compliance
- Added `IImutable` inheritance to `PierForce` class to satisfy beta-code-compliance checks. 
#447 to be actioned next milestone
> Add inheritance of IImutable class for PierForce
