ETABS_Engine/ETABS_Engine.csproj, ETABS_Engine/Modify/SetShellType.cs, ETABS_Engine/Query/EtabsShellType.cs, ETABS_oM/ETABS_oM.csproj, ETABS_oM/Enums/ShellType.cs, Etabs_Adapter/CRUD/Create.cs, Etabs_Adapter/CRUD/Read.cs, Etabs_Adapter/Helpers/Material.cs
Fixes #123
Set get get shell type for surface proeprties.
Test file here:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Etabs_Toolkit-Issue123-ShellTypeForSurfaceProps?csf=1&e=x0e6jJ
Fixes #125, see below.
=> ShellType for Surfaceproeprties, Issue123

Etabs_Adapter/CRUD/Read.cs
Closes #131
If GetSlab returns nonzero (if the shell is a wall), the toolkit calls GetWall.
Also, since we're calling GetWall, we have available the eWallPropType, so I changed the autoselect list handling bit to just test if the eWallPropType is AutoSelectList, then used GetWallAutoSelect to get the starter property for the autoselect list and read that wall property.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/ETABS_Toolkit-Issue131-ReadWallNames?csf=1&e=OHeGXj
Read SurfaceProperty now reads names of wall sections.
=> Etabs toolkit issue131 fix wall reading

ETABS_Engine/Create/Pier.cs, ETABS_Engine/Create/Spandrel.cs, ETABS_Engine/ETABS_Engine.csproj, ETABS_Engine/Modify/SetPier.cs, ETABS_Engine/Modify/SetSpandrel.cs, ETABS_Engine/Query/Pier.cs, ETABS_Engine/Query/Spandrel.cs, ETABS_oM/ETABS_oM.csproj, ETABS_oM/Elements/Pier.cs, ETABS_oM/Elements/PierForce.cs, ETABS_oM/Elements/Spandrel.cs, Etabs_Adapter/CRUD/Create.cs, Etabs_Adapter/CRUD/Read.cs, Etabs_Adapter/CRUD/ReadResults.cs, Etabs_Adapter/CRUD/UpdateObject.cs, Etabs_Adapter/Helpers/Results.cs
Issues addressed by this PR
Issue #128
Closes # 128
Added OM objects for piers and spandrels. Currently only updating panels in etabs already with pier and spandrel labels.
@IsakNaslundBh we've talked about this before...If there are issues let me know, I just had time this week for once to get these things up there and I feel like this stuff's pretty important for the vast majority of ETABs users and can save a lot of time.
Test files
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Etabs_Toolkit-Issue128-PiersandSpandrels/ETABsToolkit_Issue%23128.gh?csf=1&e=DMIxca
=> Etabs toolkit issue#128v2

ETABS_Engine/Create/Pier.cs, ETABS_Engine/Create/Spandrel.cs, ETABS_Engine/Modify/SetAutoLengthOffset.cs, ETABS_Engine/Modify/SetPier.cs, ETABS_Engine/Modify/SetSpandrel.cs, ETABS_Engine/Query/AutoLengthOffset.cs, ETABS_Engine/Query/Pier.cs, ETABS_Engine/Query/Spandrel.cs, ETABS_oM/ETABS_oM.csproj, ETABS_oM/Elements/AutoLengthOffset.cs, ETABS_oM/Elements/Pier.cs, ETABS_oM/Elements/PierForce.cs, ETABS_oM/Elements/Spandrel.cs, Etabs_Adapter/CRUD/Create.cs, Etabs_Adapter/CRUD/Read.cs
Closes #140 
Adding possibility to control RigidZone offset for the Autolength offset.
Adding AutoLengthOffset object in the Etabs_oM to control this.
Changing the previous setter, just setting a boolean, to setting this object as well, with a default RZ-factor of 1.0
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Etabs_Toolkit-Issue140-RigidZoneFactor?csf=1&e=rcgk4W
=> Etabs toolkit issue140 control auto offset rigid zone factor

Etabs_Adapter/CRUD/ReadResults.cs, Etabs_Adapter/Helpers/Results.cs
This PR is in lieu of PR #159.
The reason for this is that a conflict didn't allow the merge for #159.
I've copied over the code in this new branch; this PR mirrors that one.
Closes #135.
=> Etabs toolkit issue135 extract modal mass participation ratios solve branch conflict

ETABS_Engine/Convert/ToBHoM.cs, ETABS_Engine/ETABS_Engine.csproj, ETABS_Engine/ModelData.cs, ETABS_Engine/Query/EtabsShellType.cs, ETABS_Test/ETABS_Test.csproj, ETABS_Test/Program.cs, ETABS_Toolkit.sln, ETABS_oM/ETABS_oM.csproj, Etabs_Adapter/CRUD/Create.cs, Etabs_Adapter/CRUD/Read.cs, Etabs_Adapter/ETABSAdapter.cs, Etabs_Adapter/Etabs_Adapter.csproj, Etabs_Adapter/Helpers/LinkConstraints.cs, Etabs_Adapter/Helpers/Load.cs, Etabs_Adapter/Helpers/Material.cs, Etabs_Adapter/Helpers/Panel.cs, Etabs_Adapter/Helpers/Results.cs, Etabs_Adapter/Helpers/Section.cs
Ability to build for ETABS2016 or ETABSv17 using the Debug2016 or Debug2017 using the solution configurations dropdown.
Implemented using preprocessor directives as ETABS dll for 2016 has a different name for ETABS 2017.
=> CompatibilityForETABS17Included

Etabs_Adapter/Helpers/Load.cs
The fake bar is because I can't access ReadBar from this namespace.
Closes #186
Closes #187
Closes #172
Closes #173 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Etabs_Toolkit-Issue187-PullBarDistributedLoad?csf=1&e=NrMJUA
- Corrected problem with bar uniform loads where loads would be read with nonsense parameters.
- Added an empty element to each load containing the ETABS_id so that loads can be correlated to existing elements.
- Added a note to let the user know the element is empty but contains the correct id.
=> ETABS Toolkit: Fix read BarUniformlyDistributedLoad

Etabs_Adapter/CRUD/Create.cs, Etabs_Adapter/CRUD/Read.cs, Etabs_Adapter/Helpers/Load.cs, Etabs_Adapter/Helpers/Section.cs
Closes #160 
Closes #194 
Closes #192 
Downgraded read property error to warning, returning an empty explicit section with correct name and material for unsupported sections.
Also, bypassed nextId by setting customData to id returned by ETABS
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Etabs_Toolkit-Issue160-BarPushFailure?csf=1&e=XpKAH1
* ETABS_id now set to value assigned in ETABS
* reading bar section property no longer fails on unsupported sections
* pushing bars no longer fails if unsupported sections are defined in ETABS
=> Etabs toolkit issue160 downgrade pull section errors

ETABS_Engine/ETABS_Engine.csproj, ETABS_Engine/Modify/Upgrade.cs, ETABS_Toolkit.sln, Etabs_Adapter/Create/Bar.cs, Etabs_Adapter/Create/Error.cs, Etabs_Adapter/Create/Level.cs, Etabs_Adapter/Create/Node.cs, Etabs_Adapter/Create/Panel.cs, Etabs_Adapter/Create/_Create.cs, Etabs_Adapter/Read/Level.cs, Etabs_Adapter/Read/Material.cs, Etabs_Adapter/Read/Mesh.cs, Etabs_Adapter/Read/Node.cs, Etabs_Adapter/Read/Panel.cs, Etabs_Adapter/Read/_Read.cs
Closes #207 
Replaced mention of oM.Architecture with oM.Geometry.SettingOut
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/PR_208-UpdateGridAndLevel?csf=1&e=ew2hP8
=> Updating levels and Grids to target Geometry.SettingOut namespace instead of Architecture namespace

Etabs_Adapter/Create/_Create.cs, Etabs_Adapter/ETABSAdapter.cs
https://github.com/BHoM/BHoM_Adapter/pull/151
Closes #222
Updating adapter to align with changes in the parent BHoMAdapter
All previous scripts should still be working as before.
Link to macro testfiles:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/_Macro/Push?csf=1&e=84ibrL
=> Aligning with changes in BHoMAdapter

Etabs_Adapter/Read/Result.cs
https://github.com/BHoM/BHoM/pull/611
Closes #226 
Updating namings of MeshResult classes. Additional refactoring to make use of the ResultCollections to be done together with updates to result extractions in here https://github.com/BHoM/ETABS_Toolkit/issues/227
https://burohappold.sharepoint.com/:f:/s/BHoM/ErV6ZcpsxlxGsQam9LUokNcBpJM3GEzBrpEpZcGtdlyndA?e=7b0yu5
- Update namings of MeshResults
=> Update names of MeshResult classes

Etabs_Adapter/Create/Bar.cs
Closes #213 
Separated `SetProfile` into a `ISetProfile` interface method as well and added some try catch, while removing the now unnecessary methods for un-implemented sections.
Previously it got stuck in an infinite loop if the exact section wasn't present among the specific methods
Note: without this branch rhino will crash when you push, so don't do this in an instance of rhino with unsaved work
https://burohappold.sharepoint.com/:u:/s/BHoM/EU6TKtHLe0FJmZyiuOxbOb8BQOuyrnY2YTC3tNrHBIPG5Q?e=fvwgwB
=> Error-handling when pushing sections

Etabs_Adapter/Create/Load.cs
Closes #218 
`MassSource` could not push as its `Loadcases` did not get its Adapter_Id assigned. However the AdapterId for them in Etabs is their name, so that is what it uses now
https://burohappold.sharepoint.com/:u:/s/BHoM/ESJ3xydFul1GlPaOwhw5050BnRhUnWp8TstIknTJY8311g?e=N6jgsC
=> MassSource Push Fix

Etabs_Adapter/Create/Level.cs
Closes #217 
Levels without names are given one based on which index it has among the other levels. 
Shouldn't cause any issues as you can only push levels once and they are already ordered by height
https://burohappold.sharepoint.com/:u:/s/BHoM/EZsO9ZaRESROnH27441iHpYBSJltmCfsTt4jAAyYKzKcrg?e=2nyYGG
=> Unnamed Levels Fix

Etabs_Adapter/Create/Load.cs
Closes #177 
The distance from j is now defined as the distance from i in the `Create`. Which is how ETABS want it to be defined
https://burohappold.sharepoint.com/:u:/s/BHoM/ES3dN21bPLVPgeRB5F4k3ycBF5C8hSC5kPQNxrTAfV-w2g?e=diVrCV
=> BarVaryingDistributedLoad Extent Fix

Etabs_Adapter/Create/Material.cs
Closes #240 
Material density had wrong option in push leading to values coming over slightly skewed
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/_Macro/Push?csf=1&e=vU1hVJ
=> Fixing material density pushed with wrong "option" 

ETABS_oM/Elements/Diaphragm.cs, ETABS_oM/Elements/PierForce.cs, ETABS_oM/Fragments/AutoLengthOffset.cs, ETABS_oM/Fragments/EtabsLabel.cs, ETABS_oM/Fragments/InsertionPoint.cs, ETABS_oM/Loads/MassSource.cs, ETABS_oM/Loads/ModalCase.cs, ETABS_oM/Settings/DataBaseSettings.cs, ETABS_oM/Settings/EtabsSettings.cs
Closes #297 
remake of #300 
- Adding virtual keyword to all properties
- Adding some missing documentation lines
=> Adding virtual keyword to all oM classes

Etabs_Adapter/CRUD/Create/Load.cs, Etabs_Adapter/CRUD/Create/Loadcase.cs, Etabs_Adapter/Etabs_Adapter.csproj
Closes #291
Removes the common_engine reference as those methods will be removed and updates the using statements to their new location in Spatial_Engine
Any or none, only changes to references
=> ETABS_Toolkit: Remove Common_Engine reference

Etabs_Adapter/CRUD/Create/SectionProperty.cs, Etabs_Adapter/CRUD/Read/SectionProperty.cs
Closes #290
as title
looks worse than it is, I placed a loop around the section reading to always get the tapered sections last, as they needed the sub sections to have been read beforehand.
Not sure a loop is the pretties way (as it only ever runs twice) so welcome to suggestions.
You will notice that a lot of the pulled sections are explicit, that is as it appears that ETABS does not have a read for T-sections, a more formal check on what's missing there might be worth it @IsakNaslundBh 
https://burohappold.sharepoint.com/:f:/s/BHoM/Egd4_nUinPtCo7NtgkKXJewBqF3dWOa7Ul7Tc2GtPtCfpA?e=WYGtAr
=> Push/Pull sections with Tapered Profile

Etabs_Adapter/CRUD/Create/Link.cs, Etabs_Adapter/CRUD/Create/Material.cs, Etabs_Adapter/CRUD/Create/Panel.cs, Etabs_Adapter/CRUD/Create/SectionProperty.cs, Etabs_Adapter/CRUD/Read/SectionProperty.cs, Etabs_Adapter/Types/Comparer.cs
Closes #304 
The macro for Materials and Bars where the properties names have been set to nothing.
Note that the Material test-set complains a lot without this PR as well
https://burohappold.sharepoint.com/:f:/s/BHoM/EkpXsX-vhQNGhFACgImtiXwBstHgGrAfHbNDuyGjyWLtgg?e=fDIMRX
=> Make use of NameOrDescription Comparer when Pushing Properties

Etabs_Adapter/CRUD/Read/Bar.cs, Etabs_Adapter/CRUD/Read/Level.cs, Etabs_Adapter/CRUD/Read/Link.cs, Etabs_Adapter/CRUD/Read/Load.cs, Etabs_Adapter/CRUD/Read/Loadcase.cs, Etabs_Adapter/CRUD/Read/Material.cs, Etabs_Adapter/CRUD/Read/Mesh.cs, Etabs_Adapter/CRUD/Read/Node.cs, Etabs_Adapter/CRUD/Read/Panel.cs, Etabs_Adapter/CRUD/Read/SectionProperty.cs, Etabs_Adapter/CRUD/Read/_Read.cs
Closes #279 
request by id now works by fixing the cast from `IList` to `List<string>` and a failsafe for faulty requests has been implemented by taking the intersection of all ids in ETABS by the provided ones
https://burohappold.sharepoint.com/:f:/s/BHoM/EsHk-mo4drxEiLsc_8nhGw0BXh_gikpTfOifxNHiQKaAtw?e=Cp37ai
=> FilterRequest by ObjectId

Etabs_Adapter/CRUD/Create/Diaphragm.cs, Etabs_Adapter/CRUD/Create/Panel.cs, Etabs_Adapter/CRUD/Create/SurfaceProperty.cs, Etabs_Adapter/CRUD/Update/Node.cs, Etabs_Adapter/CRUD/Update/Panel.cs, Etabs_Adapter/CRUD/Update/_Update.cs, Etabs_Adapter/Etabs_Adapter.csproj
Closes #145 
Closes #142 
Can't move an Panel without moving it's nodes, which would move connected Panels as well. The other option would be to re-create the Panel, but that would remove load information and every other kind of information added to the panel in ETABS. So think that functionality is better left in Create.
The last resort would be to get as much data on the object within the method and reassign after recreating the Panel, but don't know if the API allows one to get and set all kinds of data, and would have to be manually updated if the API changes to retain it's Update functionality 
I don't know what Pier & Spandrel is or where I can find it in ETABS
https://burohappold.sharepoint.com/:u:/s/BHoM/EYVMwIVqAnZIrGME4-G1KcQBczx_4ytUEgcxgEIEnMDvqQ?e=Sfui9W
- All properties …
=> Update of Panel

ETABS_oM/Elements/PierForce.cs, Etabs_Adapter/CRUD/Read/Results/BarResults.cs, Etabs_Adapter/CRUD/Read/Results/GlobalResults.cs, Etabs_Adapter/CRUD/Read/Results/MeshResults.cs, Etabs_Adapter/CRUD/Read/Results/NodeResults.cs, Etabs_Adapter/CRUD/Read/Results/Result.cs
https://github.com/BHoM/BHoM/pull/912
Align with changes in Structure_oM making results immutable
Adding first filter trying to identify if "StepNum" is mode or not.
Also updated the method used for modal dynamics to one that more closely reassembles the result class returned.
https://burohappold.sharepoint.com/:f:/s/BHoM/EgTmkOTgxdxOr2rodGPhLVIBo7P8mT7QjcjM8TOGdKVDuQ?e=PBfCCt
=> Align with changes in Structure_oM making results immutable

Etabs_Adapter/CRUD/Create/Node.cs, Etabs_Adapter/CRUD/Delete/_Delete.cs, Etabs_Adapter/CRUD/Read/_Read.cs, Etabs_Adapter/CRUD/Update/Node.cs, Etabs_Adapter/ETABSAdapter.cs, Etabs_Adapter/Etabs_Adapter.csproj, dependencies.txt
For the coordinateSystem comparison
https://github.com/BHoM/BHoM_Engine/pull/1880
Closes #329 
Closes #315 
Adds warnings related to #311 
Also adds Delete
Also some extra code due to this https://github.com/BHoM/BHoM_Adapter/issues/239
And note that Update Node is slow, as I can't find any way to lock ETABS or any batch move (as every node can move in a different direction) and it does also move the things it's connected to, which might be what one would expect?
https://burohappold.sharepoint.com/:u:/s/BHoM/EchZkdNbgr9Eo7hkicvBPKYBVch1ZVDE16SxE1Fd6HGxQA?e=k2BOcX
https://burohappold.sharepoint.com/:u:/s/BHoM/EcsGb6NIFDdAoQL4FJKzGp4B5PHm4mKI7Uj842pIQXf6Uw?e=gPlfdt
=> ETABS_Toolkit: SelectionRequest, Delete and update for Node

Etabs_Adapter/CRUD/Create/Level.cs
Closes #313 
https://burohappold.sharepoint.com/:u:/s/BHoM/Ed6BQd-J0YVFpOvCapmRme4B78umJf1o-av4JswmxqT9YA?e=BTnKR0
- Change made so that the level provided with the lowest elevation is always considered the base level. No longer inserting base at level 0.
=> Fix push of Levels at or below zero

ETABS_oM/ETABS_oM.csproj, ETABS_oM/Requests/Enum/PierAndSpandrelResultType.cs, ETABS_oM/Requests/PierAndSpandrelForceRequest.cs, ETABS_oM/Results/PierForce.cs, ETABS_oM/Versioning_33.json, Etabs_Adapter/CRUD/Read/Results/PierAndSpandrelResults.cs, Etabs_Adapter/CRUD/Read/Results/Result.cs, Etabs_Adapter/CRUD/Read/_Read.cs, Etabs_Adapter/Etabs_Adapter.csproj
https://github.com/BHoM/BHoM_Adapter/pull/244
Closes #331 
Removing support for pulling results with filter request, instead raising error stating what request that should be used.
Test pulling PierForce:
https://burohappold.sharepoint.com/:f:/s/BHoM/EhPTvbEYls9GoAHZ5LAAK1MB323kFzdSJSV9DwlWcEolAg?e=rh9KTR
Testing that error messages show up:
https://burohappold.sharepoint.com/:f:/s/BHoM/EpJzc3cX8wxFlD34ESjLjX4BepFblb73yqAEWHe8l1GuDA?e=iuLZct
For testing general results functionality:
https://burohappold.sharepoint.com/:f:/s/BHoM/EqqZu_1Sr0lIkfBdRPg8TBQBBsLM3bh3YedOFyiiI5-_tA?e=Ri0dJ9
- Disabling pulling results with FIlterRequest, instead returning error stating what needs to be done
- Adding in PierAndSpandrelForceRequest for pulling PierForces
- Updating namespace of PierForce to …
=> Remove support for pulling results with filter request and Add PierAndSpandrelResultRequest

Etabs_Adapter/CRUD/Create/Link.cs, Etabs_Adapter/CRUD/Read/Link.cs
/BHoM/BHoM/pull/961
Closes #
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue921-RigidLink%20property%20rename/Test%20Rigid%20Links%20-%20multi%20adapter.gh?csf=1&web=1&e=iDXtGs
=> Renamed RigidLink master/slave to primary/secondary

Etabs_Adapter/CRUD/Read/Results/GlobalResults.cs
Closes #342
Disabling ModalDynamics extraction until fixed in #341 
https://burohappold.sharepoint.com/:f:/s/BHoM/EszNjShmWNFJpiMmQ1EdM7ABAa3i7rfMe8oa54uHFtbwxg?e=6leOup
=> Disable ModalDynamics extraction

Etabs_Adapter/CRUD/Create/SectionProperty.cs, Etabs_Adapter/CRUD/Read/SectionProperty.cs
https://github.com/BHoM/BHoM/pull/992
https://github.com/BHoM/BHoM_Engine/pull/1980
Closes #346 
From previous PR:
https://burohappold.sharepoint.com/:f:/s/BHoM/Egd4_nUinPtCo7NtgkKXJewBqF3dWOa7Ul7Tc2GtPtCfpA?e=WYGtAr
General script with a variety of sections:
https://burohappold.sharepoint.com/:f:/s/BHoM/EsoGNizz8VZAn_h4VNRhhuwBTuj98dVj4ZDK3-84ID8KGw?e=VTSafM
- Based on comments in the code I have assumed the `interpolationOrder` can only be linear.
=> Update to TaperedProfile functionality inline with Geometry_oM updates

Etabs_Adapter/ETABSAdapter.cs
Closes #362 
Fixing issue with the force refresh, in particular for ETABS18. Adding a second SelectAll before moving all elements back.
https://burohappold.sharepoint.com/:f:/s/BHoM/Eha-mq-0l55KryMeBe543YkBf2M6CQUaOaL6xgKfeFLg6Q?e=chvV7S
=> Fix force refresh for Etabs18

ETABS_Engine/ETABS_Engine.csproj
Closes #367
Changes assembly name from Etabs_Engine to ETABS_Engine to match the capitalisation used throughout the toolkit. This means that Etabs_Engine.dll will now be called ETABS_Engine.dll. Note that files in Windows are not case sensitive, so if Etabs_Engine.dll already exists when building, this name will be kept - but this should also mean that this change shouldn't cause any File Not Found errors or similar.
=> ETABS_Engine: Capitalise ETABS_Engine assembly name

Etabs_Adapter/CRUD/Update/Bar.cs
https://github.com/BHoM/BHoM_Adapter/pull/287
Closes #379 
The ETABS adapter was relying on the non-generic `AdapterId()` method to get the Id of the objects. While this is not wrong per se, that method has now been renamed to `AdapterIds()` (note the s) to highlight the fact that it may return _more than only one Id, depending on whether multiple Ids have been stored on the object_.  
As this adapter currently does not need to use that feature, this PR simply replaces it with calls to `AdapterId<T>()`.
Testing of existing functionality is needed to make sure that everything works as before.
=> Align to BHoM_Adapter's AdapterId() method change

Etabs_Adapter/CRUD/Read/Mesh.cs
Closes #384 
Also related to #352 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23385-fix-FEMesh-read-method?csf=1&web=1&e=1WOL2g
=> Fix null handling in FEMesh

Etabs_Adapter/CRUD/Read/Bar.cs, Etabs_Adapter/Convert/ToCSI/BarRelease.cs
Closes #393 
Makes sure the spring stiffness is picked up by changing the check if a DOF is released from checking if identical to free to instead check if it is not fixed.
https://burohappold.sharepoint.com/:f:/s/BHoM/Evb6D2Mx5SlCldKS1XidhaUBl2Bi4gJ-lwtbV259ropqFg?e=0sPAc7
=> Fix spring stiffness for BarReleases

Etabs_Adapter/CRUD/Create/Material.cs, Etabs_Adapter/CRUD/Read/Material.cs, Etabs_Adapter/CRUD/Read/_Read.cs, Etabs_Adapter/ETABSAdapter.cs
Closes #378 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23405-set-design-parameters-during-material-push?csf=1&web=1&e=RXiDVc
=> ETABS_Toolkit: Set material design parameters during push

Etabs_Adapter/CRUD/Read/Bar.cs
Fixed bug. Bar GUIDs are now being read correctly.
Closes #407
=> Fixed bug. Bar GUIDs are now being read correctly

Etabs_Adapter/CRUD/Read/Bar.cs, Etabs_Adapter/CRUD/Read/Link.cs, Etabs_Adapter/CRUD/Read/Load.cs, Etabs_Adapter/CRUD/Read/Loadcase.cs, Etabs_Adapter/CRUD/Read/Mesh.cs, Etabs_Adapter/CRUD/Read/Panel.cs, Etabs_Adapter/CRUD/Read/SectionProperty.cs, Etabs_Adapter/CRUD/Read/SurfaceProperty.cs, Etabs_Adapter/CRUD/Read/_Read.cs
https://github.com/BHoM/BHoM_Adapter/pull/337
intentionally using different branch names to let the Adapter PR be merged separately.
Closes #417 
Make use of the Caching system added to the Base adapter. Aim for this to speed up the push process, especially for higher level objects.
Usual test file for Push/Pull:
- https://burohappold.sharepoint.com/:f:/s/BHoM/EgweOoPLfH1Jp4af3nYl9zwBN-fusTnBgRggWimsp2knVA?e=u3D3RD
- https://burohappold.sharepoint.com/:f:/s/BHoM/EqPyIzrdkF9CvI0_e85Bo-sBrlNc1B1Z6u8lyrDBUKL-iw?e=udkEMR
The testing should simply verify that things work as good as usual.
This PR only makes backend improvements to the Adapter and should not affect existing workflows.
=> Make use of caching system in base adapter

Etabs_Adapter/AdapterActions/Execute.cs
Resolves #350
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/Burohappold_BHoM_v6.3/Structures%20-%20Execute%20commands/BuroHappold_BHoM_v6.3.beta_ExecuteCommands.gh?csf=1&web=1&e=0fKUaa
- Fixed Etabs `ClearResults` function so the model becomes unlocked.
Previous `ClearResults` command does not work but still return `true`.
Fix this bug by referring to the code of sap2000 toolkit.
=> Fix Etabs unlock/delete results function

ETABS_Toolkit.sln, Etabs_Adapter/AdapterActions/Execute.cs, Etabs_Adapter/CRUD/Create/Loadcase.cs, Etabs_Adapter/CRUD/Create/Material.cs, Etabs_Adapter/CRUD/Create/SurfaceProperty.cs, Etabs_Adapter/CRUD/Read/Link.cs, Etabs_Adapter/CRUD/Read/Load.cs, Etabs_Adapter/CRUD/Read/Loadcase.cs, Etabs_Adapter/CRUD/Read/Material.cs, Etabs_Adapter/CRUD/Read/Results/BarResults.cs, Etabs_Adapter/CRUD/Read/Results/MeshResults.cs, Etabs_Adapter/CRUD/Read/Results/NodeResults.cs, Etabs_Adapter/CRUD/Read/SectionProperty.cs, Etabs_Adapter/CRUD/Read/SurfaceProperty.cs, Etabs_Adapter/CRUD/Update/Material.cs, Etabs_Adapter/ETABSAdapter.cs, Etabs_Adapter/Etabs_Adapter.csproj, Etabs_Adapter/packages.config
Closes #420 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/%23420%20Issue%20Etabs%20Adapter%20is%20not%20able%20to%20launch%20Etabs/240205%20Etabs_Launch%20fail_Resolved.gh?csf=1&web=1&e=IGX2gI
Replaced ETABSv1 with CSiAPIv1 NuGet package. This causes the ETABS Application to be launched when the adapter component is toggled on.
ETABS adapter would fail to launch ETABS (Version 19) as reported by the user. The push/pull would only work when the ETABS application is already opened by the user manually. The reported behavior is also observed in ETABS (Version 20) which is the version installed in my machine. Replacing of NuGet Package with more updated version (which references CSI ETABS API) fixed this issue.
=> Fixes the issue of failing to launch ETABS application when the ETABS adapter is toggled on

ETABS_oM/ETABS_oM.csproj, ETABS_oM/Results/PierForce.cs, Etabs_Adapter/Etabs_Adapter.csproj
Closes #447 
https://burohappold.sharepoint.com/:u:/s/BHoM/EWEdqsW6RwlKipogK2deoTIBaMctYiF38inJzHUCDtG19g?e=opbGFs
- Updated inheritance for `PierForce` and removed inheritance of `BarForce`;
=> Change inheritance for PierForce

Etabs_Adapter/CRUD/Read/Results/NodeResults.cs
Closes #460 
ETABS Toolkit now can allow to extract joint accelerations outputs from ETABS.
[https://burohappold.sharepoint.com/:u:/s/BHoM/ESMRcVgt7RBDmxfhsz9HF_4BZOKpp9A_JYihkY1BjTNIGw?e=AJjNUE](url)
ETABS File
[https://burohappold.sharepoint.com/:i:/s/BHoM/EfzC47OrWThIof0lXaPvMX0BTg-mcMYKC1zuJkQ4Nais-A?e=uF0gSf](url)
- Added ReadNodeAcceleration Method to retrieve Abs Joint Accelerations from ETABS
=> Add Get Joint Accelerations

Etabs_Adapter/CRUD/Create/Load.cs, Etabs_Adapter/CRUD/Read/Load.cs
Closes #459 
It is now possible to push and pull Point Displacement Loads to/from ETABS (see below)
[https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23467-AddSetGetPointDisplacementLoad/Test%20Script.gh?csf=1&web=1&e=L6zLU9](url)
ETABS File
[https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23467-AddSetGetPointDisplacementLoad/Test%20Etabs%20Model.EDB?csf=1&web=1&e=UJENuT](url)
- Added SetLoad Method for Point Displacement Loads
- Added ReadLoad Method for Point Displacement Loads
=> Add Set Get Point Displacement Loads

Etabs_Adapter/CRUD/Read/Load.cs
Closes #472 
Now pull of point displacement loads works as expected 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23473-FixGetPointDispLoad/Test%20Script.gh?csf=1&web=1&e=5uSdY4
ETABS File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23473-FixGetPointDispLoad/Test%20Etabs%20Model.EDB?csf=1&web=1&e=aCjHAI
- Add missing call to ReadPointDisplacementLoad function within the main Read method
=> Fix ReadPointDisplacementLoad

ETABS_oM/ETABS_oM.csproj, ETABS_oM/Requests/PierAndSpandrelForceRequest.cs, ETABS_oM/Results/SpandrelForce.cs, Etabs_Adapter/CRUD/Read/Results/PierAndSpandrelResults.cs, Etabs_Adapter/Etabs_Adapter.csproj, Etabs_Adapter/Types/DependencyTypes.cs
Closes #430 
[https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23457-AddSpandrelForceResult/Test%20Script.gh?csf=1&web=1&e=caphlX](url)
ETABS File
[https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23457-AddSpandrelForceResult/Test%20ETABS%20Model.EDB?csf=1&web=1&e=6N8BDm](url)
- Added SpandrelForce Class to the ETABS_oM Results namespace
- Added SpandrelForce value to Enum PierAndSpandrelResultType  in the Requests namespace
- Added calls to ETABS API functions to extract Spandrel Forces from ETABS Model in the ETABS Adapter
=> Add Spandrel Force Result

Etabs_Adapter/CRUD/Update/Node.cs, Etabs_Adapter/ETABSAdapter.cs
Closes #464 
ETABS Toolkit now able to perform translational movement of ETABS models upon Update Request much faster than before (up to 7 times faster as per Test ETABS model below - i.e.: from 7 minutes to 1 minute max).
Whenever rotations or distorsions of ETABS objects are concerned, unfortunately ETABS API limitations still prevent BHoM from carrying out a correct update of ETABS panel objects.
More work is required to find out a solution to this problem.
Video Demonstration - Issue
https://burohappold.sharepoint.com/:v:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23476-ImproveMoveObjectsAlgorithm/Moving%20BHoM%20Algorithm%20Issue.mp4?csf=1&web=1&e=XrufhL
Video Demonstration - Solution
https://burohappold.sharepoint.com/:v:/r/sites/BHoM/02_Current/12_Scrip …
=> Improve Move Objects Update Feature

Etabs_Adapter/ETABSAdapter.cs, Etabs_Adapter/Etabs_Adapter.csproj, Etabs_Adapter/Types/PriorityTypes.cs
https://github.com/BHoM/BHoM_Adapter/pull/393
Closes #435 
ETABS Toolkit now able to push objects and levels together by using priorities on top of dependencies for sorting the objects to push.
Video Demonstration - Issue
https://burohappold.sharepoint.com/:v:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23480-AddPriorityTypesForPush/Push%20Levels%20Issue.mp4?csf=1&web=1&e=7cEacd
Video Demonstration - Solution
https://burohappold.sharepoint.com/:v:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23480-AddPriorityTypesForPush/Push%20Levels%20Sorted.mp4?csf=1&web=1&e=cDUbje
Json File
https://burohappold.sharepoint.com/sites/BHoM/_layouts/15/download.aspx?UniqueId=aa695dbddee44123b35aecc6843d658a&e=mvnMou …
=> Fix Issue with Pushing Levels by using PriorityTypes

ETABS_oM/ETABS_oM.csproj, Etabs_Adapter/AdapterActions/Execute.cs, Etabs_Adapter/ETABSAdapter.cs
Closes #413 
ETABS Toolkit now allows to retrieve the full filepath of the ETABS Model as a public attribute of the ETABSAdapter class.
ETABS File
- Added public and read-only attribute FilePath to the ETABSAdapter Class
- Added assignment of the FilePath attribute in the Constructor of the ETABSAdapter Class
=> Get ETABS File Path

Etabs_Adapter/CRUD/Read/Results/GlobalResults.cs
https://github.com/BHoM/BHoM/pull/1639
Closes #138 
ETABS Toolkit now able to extract Story Drifts from ETABS Model based on input loadcase/loadcombo.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23477-ExtractStoryDrifts/Test%20Script.gh?csf=1&web=1&e=lrVtVc
ETABS File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23477-ExtractStoryDrifts/Test%20ETABS%20Model.EDB?csf=1&web=1&e=Frkg7n
- Added StoryDrift Class to BHoM Structure Global Results
- Added GetStoryDrifts Method to ETABS Toolkit Read Global Results
=> Extract Story Drifts

Etabs_Adapter/CRUD/Read/Results/MeshResults.cs, Etabs_Adapter/ETABSAdapter.cs
Closes #463 
ETABS Toolkit now can allow to extract Shell Von Mises Stress outputs from ETABS.
Files Folder
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23471-ExtractMeshVonMisesStresses?csf=1&web=1&e=OpP1iW
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23471-ExtractMeshVonMisesStresses/Test%20Script.gh?csf=1&web=1&e=AFd4Si
ETABS File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23471-ExtractMeshVonMisesStresses/Test%20ETABS%20Model.EDB?csf=1&web=1&e=6fgDcc
Excel File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit …
=> Extract Mesh VonMises Stresses

Etabs_Adapter/CRUD/Create/Load.cs
Closes #458
[https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23466-AddSetGetDifferentialTempLoad/Test%20Script.gh?csf=1&web=1&e=R86dQg](url)
ETABS File
[https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23466-AddSetGetDifferentialTempLoad/Test%20Etabs%20Model.EDB?csf=1&web=1&e=OisjcH](url)
- Added SetLoad Method for FrameObj Differential Temperature Load
- Added SetLoad Method for AreaObj Differential Temperature Load
=> Add Set Get Differential Temp Load

Etabs_Adapter/CRUD/Create/Opening.cs, Etabs_Adapter/CRUD/Read/Opening.cs, Etabs_Adapter/CRUD/Read/Panel.cs, Etabs_Adapter/CRUD/Read/_Read.cs, Etabs_Adapter/Etabs_Adapter.csproj, Etabs_Adapter/Types/DependencyTypes.cs
Closes #375 
ETABS Toolkit now allows to push and pull Opening objects.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23479-AddSupportForStructureOpenings/Test%20Script.gh?csf=1&web=1&e=fdeQlU
ETABS File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23479-AddSupportForStructureOpenings/Test%20ETABS%20Model.EDB?csf=1&web=1&e=xXim64
- Added Opening.cs class in Read and Create packages
=> Add Adapter Support for Structure Openings

Etabs_Adapter/CRUD/Create/Bar.cs, Etabs_Adapter/ETABSAdapter.cs
Closes #482 
ETABS Toolkit now able to push bars to ETABS 21 by skipping not-working API function by checking running ETABS version.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23487-FixBugPushBarsToETABS21/BHoM%207.3.1%20Test%20-%20Bar%20Object%20Push%20to%20ETABS%2021%201.gh?csf=1&web=1&e=FQ2bKd
ETABS File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23487-FixBugPushBarsToETABS21/Test%20ETABS%20Model.EDB?csf=1&web=1&e=JE5bz2
- Added extraction of ETABS Version number as a string in Adapter constructor
- Use of ETABS Version Number in the create() method for bars to prevent api bug from popping up
=> Fix Bug when Pushing Bars to ETABS21

Etabs_Adapter/ETABSAdapter.cs
https://github.com/BHoM/BHoM_Adapter/pull/398
Closes #491 
[Installer](https://burohappold.sharepoint.com/:f:/s/BHoM/EngdHnX9w_5Jr0c2sk7UwmkBUM7VocNTlrLZjH2NZEYk4A?e=oLkZBp)
As a minimum test for each adapter:
1. Run the adapter in Rhino 8;
2. Push a `Bar`;
3. Run an `Execute` method;
4. Pull a result.
- Implemented `GetActiveObject` method from the BHoM_Adapter;
- Adapter does not function in .NET Core environments but can be run in Rhino 8 by changing the .NET environment to Framework: https://www.rhino3d.com/en/docs/guides/netcore/ .
=> Implement Adapter_Engine for GetActiveObject
